// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Submarine.Api.Models.Database;

#nullable disable

namespace Submarine.Api.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20260711210133_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Submarine.Core.Provider.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Provider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submarine.Core.Provider.BittorrentTracker", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.Property<int?>("MinimumSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeasonPackSeedTime")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("SeedTime")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BittorrentTracker");
                });

            modelBuilder.Entity("Submarine.Core.Provider.UsenetIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.HasDiscriminator().HasValue("UsenetIndexer");
                });
#pragma warning restore 612, 618
        }
    }
}
