// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Submarine.Api.Models.Database;

#nullable disable

namespace Submarine.Api.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20260712065732_AddNotificationConnections")]
    partial class AddNotificationConnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("EpisodeFileEpisodes", b =>
                {
                    b.Property<int>("EpisodesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EpisodesId", "FilesId");

                    b.HasIndex("FilesId");

                    b.ToTable("EpisodeFileEpisodes");
                });

            modelBuilder.Entity("Submarine.Core.Config.DownloadConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableFailedDownloadHandling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RedownloadFailedReleases")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemoveFailedFromClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadConfigs");
                });

            modelBuilder.Entity("Submarine.Core.Config.IndexerConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumAgeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RssSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IndexerConfigs");
                });

            modelBuilder.Entity("Submarine.Core.Config.MediaManagementConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportExtraFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumFreeSpaceMb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseHardlinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WriteNfo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaManagementConfigs");
                });

            modelBuilder.Entity("Submarine.Core.Config.NamingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimeEpisodeFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RenameEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardEpisodeFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NamingConfigs");
                });

            modelBuilder.Entity("Submarine.Core.Config.SecurityConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SecurityConfigs");
                });

            modelBuilder.Entity("Submarine.Core.DecisionEngine.CustomFormats.CustomFormatConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomFormats");
                });

            modelBuilder.Entity("Submarine.Core.DecisionEngine.Filter.ReleaseFilterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReleaseFilters");
                });

            modelBuilder.Entity("Submarine.Core.Download.BlocklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indexer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Blocklist");
                });

            modelBuilder.Entity("Submarine.Core.Download.DownloadClientConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadClients");
                });

            modelBuilder.Entity("Submarine.Core.Download.RemotePathMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RemotePathMappings");
                });

            modelBuilder.Entity("Submarine.Core.Download.TrackedDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadClientConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EpisodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Imported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indexer")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaVersionId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("TrackedDownloads");
                });

            modelBuilder.Entity("Submarine.Core.History.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Submarine.Core.ImportList.ImportList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportLists");
                });

            modelBuilder.Entity("Submarine.Core.Library.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsoluteEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Submarine.Core.Library.MediaVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Submarine.Core.Library.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Submarine.Core.Library.RootFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("RootFolders");
                });

            modelBuilder.Entity("Submarine.Core.Library.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Submarine.Core.Library.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataProvider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numbering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeasonFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TvdbId")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.EpisodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NamedFromPlaceholder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaVersionId");

                    b.ToTable("EpisodeFiles");
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.MovieFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaVersionId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieFiles");
                });

            modelBuilder.Entity("Submarine.Core.Notification.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnGrab")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnImport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnRename")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Connections");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Connection");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submarine.Core.Profile.DelayProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BypassIfHighestQuality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredProtocol")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TorrentDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsenetDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DelayProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Profile.LanguageProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cutoff")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LanguageProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Profile.QualityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cutoff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormatScores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Profile.ReleaseProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Ignored")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Indexer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Required")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReleaseProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Provider.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Provider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submarine.Core.Quality.ReleaseGroupQualityOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseGroup")
                        .IsUnique();

                    b.ToTable("ReleaseGroupQualityOverrides");
                });

            modelBuilder.Entity("Submarine.Core.Tag.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Submarine.Core.Notification.DiscordConnection", b =>
                {
                    b.HasBaseType("Submarine.Core.Notification.Connection");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DiscordConnection");
                });

            modelBuilder.Entity("Submarine.Core.Notification.TelegramConnection", b =>
                {
                    b.HasBaseType("Submarine.Core.Notification.Connection");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TelegramConnection");
                });

            modelBuilder.Entity("Submarine.Core.Notification.WebhookConnection", b =>
                {
                    b.HasBaseType("Submarine.Core.Notification.Connection");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("WebhookConnection");
                });

            modelBuilder.Entity("Submarine.Core.Provider.BittorrentTracker", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.Property<int?>("MinimumSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeasonPackSeedTime")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("SeedTime")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BittorrentTracker");
                });

            modelBuilder.Entity("Submarine.Core.Provider.NewznabIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.PrimitiveCollection<string>("AnimeCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("NewznabIndexer");
                });

            modelBuilder.Entity("Submarine.Core.Provider.TorznabIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.PrimitiveCollection<string>("AnimeCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SeasonPackSeedTime")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("SeedTime")
                        .HasColumnType("INTEGER");

                    b.ToTable("Providers", t =>
                        {
                            t.Property("AnimeCategories")
                                .HasColumnName("TorznabIndexer_AnimeCategories");

                            t.Property("Categories")
                                .HasColumnName("TorznabIndexer_Categories");

                            t.Property("MinimumSeeders")
                                .HasColumnName("TorznabIndexer_MinimumSeeders");

                            t.Property("SeasonPackSeedTime")
                                .HasColumnName("TorznabIndexer_SeasonPackSeedTime");

                            t.Property("SeedRatio")
                                .HasColumnName("TorznabIndexer_SeedRatio");

                            t.Property("SeedTime")
                                .HasColumnName("TorznabIndexer_SeedTime");
                        });

                    b.HasDiscriminator().HasValue("TorznabIndexer");
                });

            modelBuilder.Entity("Submarine.Core.Provider.UsenetIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.HasDiscriminator().HasValue("UsenetIndexer");
                });

            modelBuilder.Entity("EpisodeFileEpisodes", b =>
                {
                    b.HasOne("Submarine.Core.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Submarine.Core.MediaFile.EpisodeFile", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.Download.BlocklistItem", b =>
                {
                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.Download.TrackedDownload", b =>
                {
                    b.HasOne("Submarine.Core.Library.MediaVersion", null)
                        .WithMany()
                        .HasForeignKey("MediaVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.History.HistoryEvent", b =>
                {
                    b.HasOne("Submarine.Core.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.Library.Episode", b =>
                {
                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.Library.MediaVersion", b =>
                {
                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany("Versions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany("Versions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Submarine.Core.Library.Season", b =>
                {
                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.EpisodeFile", b =>
                {
                    b.HasOne("Submarine.Core.Library.MediaVersion", null)
                        .WithMany()
                        .HasForeignKey("MediaVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.MovieFile", b =>
                {
                    b.HasOne("Submarine.Core.Library.MediaVersion", null)
                        .WithMany()
                        .HasForeignKey("MediaVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany("Files")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.Profile.QualityProfile", b =>
                {
                    b.OwnsMany("Submarine.Core.Profile.QualityProfileItem", "Items", b1 =>
                        {
                            b1.Property<int>("QualityProfileId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Allowed");

                            b1.HasKey("QualityProfileId", "__synthesizedOrdinal");

                            b1.ToTable("QualityProfiles");

                            b1
                                .ToJson("Items")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("QualityProfileId");

                            b1.OwnsOne("Submarine.Core.Quality.QualityResolutionModel", "Quality", b2 =>
                                {
                                    b2.Property<int>("QualityProfileItemQualityProfileId");

                                    b2.Property<int>("QualityProfileItem__synthesizedOrdinal");

                                    b2.Property<int?>("Resolution");

                                    b2.Property<int?>("Source");

                                    b2.HasKey("QualityProfileItemQualityProfileId", "QualityProfileItem__synthesizedOrdinal");

                                    b2.ToTable("QualityProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("QualityProfileItemQualityProfileId", "QualityProfileItem__synthesizedOrdinal");
                                });

                            b1.Navigation("Quality")
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Submarine.Core.Library.Movie", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Submarine.Core.Library.Series", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
