// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Submarine.Api.Models.Database;

#nullable disable

namespace Submarine.Api.Migrations.Postgres
{
    [DbContext(typeof(PostgresDatabaseContext))]
    [Migration("20260712000237_AddImportLists")]
    partial class AddImportLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Submarine.Core.Config.MediaManagementConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("ImportExtraFiles")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumFreeSpaceMb")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseHardlinks")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MediaManagementConfigs");
                });

            modelBuilder.Entity("Submarine.Core.Config.NamingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AnimeEpisodeFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovieFolderFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovieFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RenameEpisodes")
                        .HasColumnType("boolean");

                    b.Property<string>("SeasonFolderFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesFolderFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandardEpisodeFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NamingConfigs");
                });

            modelBuilder.Entity("Submarine.Core.DecisionEngine.CustomFormats.CustomFormatConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CustomFormats");
                });

            modelBuilder.Entity("Submarine.Core.DecisionEngine.Filter.ReleaseFilterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Field")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("ReleaseFilters");
                });

            modelBuilder.Entity("Submarine.Core.Download.DownloadClientConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DownloadClients");
                });

            modelBuilder.Entity("Submarine.Core.Download.TrackedDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownloadClientConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("EpisodeIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("Imported")
                        .HasColumnType("boolean");

                    b.Property<string>("Indexer")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Languages")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("OutputPath")
                        .HasColumnType("text");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("TrackedDownloads");
                });

            modelBuilder.Entity("Submarine.Core.History.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Languages")
                        .HasColumnType("integer[]");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .HasColumnType("text");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeriesId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Submarine.Core.ImportList.ImportList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaKind")
                        .HasColumnType("integer");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("RootFolderId")
                        .HasColumnType("integer");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportLists");
                });

            modelBuilder.Entity("Submarine.Core.Library.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbsoluteEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AirDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeFileId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeFileId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Submarine.Core.Library.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<int?>("MovieFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer");

                    b.Property<string>("SortTitle")
                        .HasColumnType("text");

                    b.Property<string>("Studio")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieFileId");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Submarine.Core.Library.RootFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MediaKind")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("RootFolders");
                });

            modelBuilder.Entity("Submarine.Core.Library.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Submarine.Core.Library.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.Property<string>("Network")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer");

                    b.Property<bool>("SeasonFolder")
                        .HasColumnType("boolean");

                    b.Property<string>("SortTitle")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TvdbId")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.EpisodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("Languages")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("NamedFromPlaceholder")
                        .HasColumnType("boolean");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("text");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EpisodeFiles");
                });

            modelBuilder.Entity("Submarine.Core.MediaFile.MovieFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Edition")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Languages")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseGroup")
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MovieFiles");
                });

            modelBuilder.Entity("Submarine.Core.Profile.LanguageProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cutoff")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Languages")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LanguageProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Profile.QualityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cutoff")
                        .HasColumnType("integer");

                    b.Property<string>("FormatScores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("Submarine.Core.Provider.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Provider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Submarine.Core.Tag.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Submarine.Core.Provider.BittorrentTracker", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.Property<int?>("MinimumSeeders")
                        .HasColumnType("integer");

                    b.Property<long?>("SeasonPackSeedTime")
                        .HasColumnType("bigint");

                    b.Property<float?>("SeedRatio")
                        .HasColumnType("real");

                    b.Property<long?>("SeedTime")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("BittorrentTracker");
                });

            modelBuilder.Entity("Submarine.Core.Provider.NewznabIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.PrimitiveCollection<List<int>>("AnimeCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("Categories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasDiscriminator().HasValue("NewznabIndexer");
                });

            modelBuilder.Entity("Submarine.Core.Provider.TorznabIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.PrimitiveCollection<List<int>>("AnimeCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("Categories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("MinimumSeeders")
                        .HasColumnType("integer");

                    b.Property<long?>("SeasonPackSeedTime")
                        .HasColumnType("bigint");

                    b.Property<float?>("SeedRatio")
                        .HasColumnType("real");

                    b.Property<long?>("SeedTime")
                        .HasColumnType("bigint");

                    b.ToTable("Providers", t =>
                        {
                            t.Property("AnimeCategories")
                                .HasColumnName("TorznabIndexer_AnimeCategories");

                            t.Property("Categories")
                                .HasColumnName("TorznabIndexer_Categories");

                            t.Property("MinimumSeeders")
                                .HasColumnName("TorznabIndexer_MinimumSeeders");

                            t.Property("SeasonPackSeedTime")
                                .HasColumnName("TorznabIndexer_SeasonPackSeedTime");

                            t.Property("SeedRatio")
                                .HasColumnName("TorznabIndexer_SeedRatio");

                            t.Property("SeedTime")
                                .HasColumnName("TorznabIndexer_SeedTime");
                        });

                    b.HasDiscriminator().HasValue("TorznabIndexer");
                });

            modelBuilder.Entity("Submarine.Core.Provider.UsenetIndexer", b =>
                {
                    b.HasBaseType("Submarine.Core.Provider.Provider");

                    b.HasDiscriminator().HasValue("UsenetIndexer");
                });

            modelBuilder.Entity("Submarine.Core.Download.TrackedDownload", b =>
                {
                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.History.HistoryEvent", b =>
                {
                    b.HasOne("Submarine.Core.Library.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.Library.Episode", b =>
                {
                    b.HasOne("Submarine.Core.MediaFile.EpisodeFile", null)
                        .WithMany()
                        .HasForeignKey("EpisodeFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.Library.Movie", b =>
                {
                    b.HasOne("Submarine.Core.MediaFile.MovieFile", null)
                        .WithMany()
                        .HasForeignKey("MovieFileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Submarine.Core.Library.Season", b =>
                {
                    b.HasOne("Submarine.Core.Library.Series", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Submarine.Core.Profile.QualityProfile", b =>
                {
                    b.OwnsMany("Submarine.Core.Profile.QualityProfileItem", "Items", b1 =>
                        {
                            b1.Property<int>("QualityProfileId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("Allowed");

                            b1.HasKey("QualityProfileId", "__synthesizedOrdinal");

                            b1.ToTable("QualityProfiles");

                            b1
                                .ToJson("Items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QualityProfileId");

                            b1.OwnsOne("Submarine.Core.Quality.QualityResolutionModel", "Quality", b2 =>
                                {
                                    b2.Property<int>("QualityProfileItemQualityProfileId");

                                    b2.Property<int>("QualityProfileItem__synthesizedOrdinal");

                                    b2.Property<int?>("Resolution");

                                    b2.Property<int?>("Source");

                                    b2.HasKey("QualityProfileItemQualityProfileId", "QualityProfileItem__synthesizedOrdinal");

                                    b2.ToTable("QualityProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("QualityProfileItemQualityProfileId", "QualityProfileItem__synthesizedOrdinal");
                                });

                            b1.Navigation("Quality")
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Submarine.Core.Library.Series", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
