// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Submarine.Mappings.Database;

#nullable disable

namespace Submarine.Mappings.Migrations
{
    [DbContext(typeof(MappingsDatabaseContext))]
    [Migration("20260711212048_AddAniListMappings")]
    partial class AddAniListMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Submarine.Mappings.Models.AniListMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbsoluteOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvdbSeason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AniListId")
                        .IsUnique();

                    b.HasIndex("TvdbId");

                    b.ToTable("AniListMappings");
                });

            modelBuilder.Entity("Submarine.Mappings.Models.SceneEpisodeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SceneEpisodeMappings");
                });

            modelBuilder.Entity("Submarine.Mappings.Models.SceneMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SceneSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SceneMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
