// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Submarine.Mappings.Database;

#nullable disable

namespace Submarine.Mappings.Migrations
{
    [DbContext(typeof(MappingsDatabaseContext))]
    partial class MappingsDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Submarine.Mappings.Models.SceneEpisodeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SceneEpisodeMappings");
                });

            modelBuilder.Entity("Submarine.Mappings.Models.SceneMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SceneSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SceneMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
