<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="../Submarine.Core/Submarine.Core.csproj" />
		<ProjectReference Include="../Submarine.Contracts/Submarine.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AngleSharp" />
		<PackageReference Include="BencodeNET" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.PeriodicBatching" />
		<PackageReference Include="YamlDotNet" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Submarine.Infrastructure.Tests" />
		<InternalsVisibleTo Include="Submarine.Api.Tests" />
		<InternalsVisibleTo Include="Submarine.Api.IntegrationTests" />
	</ItemGroup>

</Project>
