<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="BencodeNET" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Submarine.Core.Tests" />
	</ItemGroup>

</Project>
