// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Submarine.Mappings.Data;

#nullable disable

namespace Submarine.Mappings.Migrations.Postgres
{
    [DbContext(typeof(PostgresMappingsDbContext))]
    partial class PostgresMappingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Submarine.Mappings.Entities.AniListMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsoluteOffset")
                        .HasColumnType("integer");

                    b.Property<int>("AniListId")
                        .HasColumnType("integer");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeStart")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<int>("TvdbSeason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AniListId")
                        .IsUnique();

                    b.HasIndex("TvdbId", "TvdbSeason");

                    b.ToTable("AniListMappings", (string)null);
                });

            modelBuilder.Entity("Submarine.Mappings.Entities.SceneEpisodeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SceneEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SceneSeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TvdbId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("SceneEpisodeMappings", (string)null);
                });

            modelBuilder.Entity("Submarine.Mappings.Entities.SceneMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("EpisodeOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("SceneSeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SearchTitle")
                        .HasColumnType("text");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TvdbId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("SceneMappings", (string)null);
                });

            modelBuilder.Entity("Submarine.Mappings.Entities.SceneNameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TvdbId", "SceneName")
                        .IsUnique();

                    b.ToTable("SceneNames", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
