<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
		<OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
		<OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)/../..</OpenApiDocumentsDirectory>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Ical.Net" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../Submarine.Infrastructure/Definitions/**" CopyToOutputDirectory="PreserveNewest" LinkBase="definitions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Submarine.Infrastructure/Submarine.Infrastructure.csproj" />
	</ItemGroup>

	<Target Name="RenameOpenApiDocument" AfterTargets="GenerateOpenApiDocuments" Condition="Exists('$(OpenApiDocumentsDirectory)/$(MSBuildProjectName)_openapi.json')">
		<Move SourceFiles="$(OpenApiDocumentsDirectory)/$(MSBuildProjectName)_openapi.json" DestinationFiles="$(OpenApiDocumentsDirectory)/openapi.json" />
	</Target>

</Project>
