<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	<NoWarn>$(NoWarn);xUnit1051</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Submarine.Infrastructure/Submarine.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

</Project>
