name: Unit Test Action
on: [push, pull_request]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend
      - name: Run Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
        working-directory: backend
      - name: Run Test
        run: dotnet test --no-build --verbosity normal
        working-directory: backend
